#pragma once

#define DANSANDU_JOURNEY_INTERNAL_CONCATENATE_INNER(a, b) a##b

#define DANSANDU_JOURNEY_INTERNAL_CONCATENATE(a, b) DANSANDU_JOURNEY_INTERNAL_CONCATENATE_INNER(a, b)

#define DANSANDU_JOURNEY_UNIQUE_NAME DANSANDU_JOURNEY_INTERNAL_CONCATENATE(dansandu_journey_unique_name, __COUNTER__)
