#pragma once

#define DANSANDU_JOURNEY_INTERNAL_CONCATENATE_INNER(a, b) a##b

#define DANSANDU_JOURNEY_INTERNAL_CONCATENATE(a, b) DANSANDU_JOURNEY_INTERNAL_CONCATENATE_INNER(a, b)

#define DANSANDU_JOURNEY_UNIQUE_NAME(prefix) DANSANDU_JOURNEY_INTERNAL_CONCATENATE(prefix, __COUNTER__)
